@startuml

Tablero "1" *-- "6" Continente
Tablero -> Batalla

class Tablero {
	- paises: List

	+ atacar(nombrePaisAtacante, nombrePaisDefensor, cantidadDeEjercitoAtacante): List
	+ buscarPais(nombrePais): Pais
	+ buscarContinente(nombreContinente): Continente
	+ ejercitosAdicionalesPorContinentesControlados(jugador): int
	+ controlaContinente(jugador, nombreContinente): boolean
	+ poseeUnaCantidadDePaisesEnContinente(jugador, cantidadDePaises, nombreContinente): boolean

}

class Batalla {
	- paisAtacante: Pais
    - paisDefensor: Pais

	+ Batalla(paisAtacante, paisDefensor): Batalla
	+ atacar(cantidadEjercito): List
}

class Continente {
	- nombre: String
    - paises: List
    - ejercitos: int
	+ Continente(nombreContinente, listaPaises, ejercitosAdicionales): Continente
	+ cantidadDePaises(): int
	+ cantidadDePaisesControlados(jugador): int
	+ ejercitosAdicionalesPorContinentesControlados(jugador, sumaEjercitos): int
	+ jugadorControlaContinente(jugador): boolean
}

@enduml