@startuml
title: Ataque exitoso entre países.
activate ":Juego"
":Juego" -> "pedro:Jugador" : jugarTurno()
activate "pedro:Jugador"
"pedro:Jugador" -> ":Juego" : atacar (String,String,cantidadEjercito)
deactivate "pedro:Jugador"

":Juego" -> ":Tablero" : atacar (String, String, cantidadEjercito)
activate ":Tablero"
":Tablero" -> ":Batalla": atacar (cantidadEjercito)
activate ":Batalla"
":Batalla" -> "paisAtacante:Pais": atacar(paisDefensa,cantidadEjercito)
activate "paisAtacante:Pais"
"paisAtacante:Pais" -> "paisDefensor:Pais": esLimitrofe(paisAtacante)
activate "paisDefensor:Pais"
"paisDefensor:Pais" --> "paisAtacante:Pais": true
deactivate "paisDefensor:Pais"
"paisAtacante:Pais" -> "ataque:Ejercito": atacar(cantidadEjercito)
activate "ataque:Ejercito"
"ataque:Ejercito" -> ":Dado": tirarDado(cantidadEjercito)
activate ":Dado"
":Dado" --> "ataque:Ejercito": dadosAtaque
deactivate ":Dado"
"ataque:Ejercito" --> "paisAtacante:Pais": dadosAtaque
deactivate "ataque:Ejercito"
"paisAtacante:Pais" --> ":Batalla": dadosAtaque
deactivate "paisAtacante:Pais"
":Batalla" -> "paisDefensor:Pais": defender()
activate "paisDefensor:Pais"
"paisDefensor:Pais" -> "defensa:Ejercito": defender()
activate "defensa:Ejercito"
"defensa:Ejercito" -> ":Dado": tirarDado()
activate ":Dado"
":Dado" --> "defensa:Ejercito": dadosDefensa
deactivate ":Dado"
"defensa:Ejercito" --> "paisDefensor:Pais": dadosDefensa
deactivate "defensa:Ejercito"
"paisDefensor:Pais" --> ":Batalla": dadosDefensa
deactivate "paisDefensor:Pais"

":Batalla" -> "paisDefensor:Pais" : sacarFicha(cantidad)
            activate "paisDefensor:Pais"
"paisDefensor:Pais" -> "defensa:Ejercito": sacarFicha(cantidad)
activate "defensa:Ejercito"
deactivate "defensa:Ejercito"
deactivate "paisDefensor:Pais"

":Batalla" -> "paisAtacante:Pais" : sacarFicha(cantidad)
            activate "paisAtacante:Pais"
"paisAtacante:Pais" -> "ataque:Ejercito": sacarFicha(cantidad)
activate "ataque:Ejercito"
deactivate "ataque:Ejercito"
deactivate "paisAtacante:Pais"
":Batalla" -> "paisDefensor:Pais" : establecerDueño(paisAtacante)
            activate "paisDefensor:Pais"
"paisDefensor:Pais" -> "defensa:Ejercito": quedoSinEjercito()
activate "defensa:Ejercito"
"defensa:Ejercito" --> "paisDefensor:Pais": true
deactivate "defensa:Ejercito"


"paisDefensor:Pais" -> ":Jugador": desocupar()
activate ":Jugador"
deactivate ":Jugador"
"paisDefensor:Pais" -> "paisAtacante:Pais": nuevoDueño()
activate "paisAtacante:Pais"
"paisAtacante:Pais" --> "paisDefensor:Pais": pedro
deactivate "paisAtacante:Pais"
deactivate "paisDefensor:Pais"
deactivate ":Batalla"
deactivate ":Tablero"
deactivate "pedro:Jugador"
@enduml